### ISSUE TITLE
The Checkout SDK integrations are being phased out

### ISSUE THREAD

**Issue by blindgaenger** [Adyen/adyen-react-native#10]
**Is your feature request related to a problem? Please describe.**
The [Adyen documentation warns](https://docs.adyen.com/online-payments/classic-integrations/checkout-sdks) that the **Checkout SDK** integrations are being phased out in 2022. As an alternative the pre-build UIs like **Drop-in or Components** should be used.

This project is called "Adyen **Checkout** React Native SDK", which implies it uses the Checkout SDK which is being phased out.
At the same time the decscription mentions **Adyen Components**, which seems to be the correct solution.

I'm in search of an Adyen integration for React Native and confused if I should use this SDK for new projects.

**Describe the solution you'd like**
Mention in the README clearly the status of this project.

**Describe alternatives you've considered**
Change the name of the SDK. I assume "Checkout SDK" is the Adyen product name.

**Additional context**
![image](https://user-images.githubusercontent.com/14903/170027117-f1985fe4-6477-4795-8f11-c39d8e48e1b4.png)

**Comment by descorp** [comment]
Hi @blindgaenger 

Sorry for the long reply, somehow your question escaped our attention.

> I'm in search of an Adyen integration for React Native and confused if I should use this SDK for new projects.

You should definitely consider this SDK for a new project. 😄 

> Mention in the README clearly the status of this project.

Project is in BETA mode - this means that we are actively developing, actively looking for a feedback, but might yet miss some of the features available on web / ios / android SDKs.

> Change the name of the SDK. I assume "Checkout SDK" is the Adyen product name.

The naming a bit confusing here, I must admit 😅
`Checkout SDK` is indeed name of a first iteration of "native" SDKs from Adyen that is deprecated this year - because of that our official documentation referes for "modern" SDK as "Components and Drop-in".

Created PR to update the title!
Thanks for a feedback 💚

**Comment by descorp** [comment]
This repo's README, iOS and Android were updated!
Thanks for feedback @blindgaenger
