### ISSUE TITLE
Remove paymentMethods from AdyenCheckout props

### ISSUE THREAD

**Issue by kpoelhekke** [Adyen/adyen-react-native#151]
**Is your feature request related to a problem? Please describe.**
Currently `paymentMethods` is part of the `AdyenCheckout` props. In our situation the `paymentMethods` can differ everytime the `start` method is called, because they are dependent on for example the amount that is being transferred. This means that before every `start` call we will fetch the payment methods for that specific transaction. In the current situation we have to fetch the payment methods and then wait for the `AdyenCheckout` component to be rerendered before we can call the `start` method, otherwise the `paymentMethods` in the `start` function are stale.

Furthermore in the current example the `paymentMethods` are provided by `AdyenCheckoutContext` and the `PaymentMethodsContext`, which doesn't really make sense because one way would be enough.

**Describe the solution you'd like**
Since the `paymentMethods` are only used in the `start` method itself it would be better to just pass them as an argument of that function.

**Describe alternatives you've considered**
Waiting for a rerender to happen and triggering the `start` method in a `useEffect` once the `paymentMethods` have updated.

**Additional context**
I can make a proposal for this if necessary!

**Comment by descorp** [comment]
Hey @kpoelhekke 

Thanks for your feedback!
This project is in BETA mode since Adyen is still learning our ways in React Native and looking for a perfect foundation for the SDK. We are always welcome to feedback!

> Since the paymentMethods are only used in the start method itself it would be better to just pass them as an argument of that function.

This is true at the current moment. 
Our main goal was to mimic the API of [our Web SDK](https://github.com/Adyen/adyen-web/blob/master/packages/playground/src/pages/Dropin/manual.js#L9-L20), but if it is causing limitations on your side, we are open to reconsidering.

> Furthermore in the current example the paymentMethods are provided by AdyenCheckoutContext and the PaymentMethodsContext, which doesn't really make sense because one way would be enough.

`PaymentMethodsContext` is part of an example app code. It is not necessary for implementation.
If you have ideas on how to improve the example app - please share 💚

>  In the current situation we have to fetch the payment methods and then wait for the AdyenCheckout component to be rerendered before we can call the start method, otherwise the paymentMethods in the start function are stale.

Maybe a silly question:
Can you use condition for rendering this?

```js
    <View>
      {freshPaymentMethods ? (
        <CheckoutView paymentMethods={freshPaymentMethods} />
      ) : (
        <LoadingPaymentMethodsStateView />
      )}
    </View>
```

> I can make a proposal for this if necessary!

This would be nice indeed! Thank you for your contribution 💚

**Comment by kpoelhekke** [comment]
Hi @descorp, 

Thanks for the reply. It might indeed be possible to fetch the payment methods a bit earlier and show a loading state. I'll investigate. For now we have lowered the priority of implementing this library into our codebase as we want to wait voor version 1.0 first. If we still run into problems implementing it, I'll try and make a proposal. Thanks for your help so far! 🙏

**Comment by descorp** [comment]
I'll close this ticket for now. Please feel free to reopen it.
