### ISSUE TITLE
[Android] Brand icons are wrong on initial load

### ISSUE THREAD

**Issue by moaeadw** [Adyen/adyen-react-native#265]
**Describe the bug**
Sending the current brands (anything longer than 4 seems to cause this) 
`brands: ['visa', 'mc', 'amex', 'dankort', 'maestro', 'dankort'],`
will cause the app to render wrong icons on android.

**To Reproduce**
1. Select a checkout with `brands: ['visa', 'mc', 'amex', 'dankort', 'maestro', 'dankort']` in card
2. Click on pay and see the icons 

**Expected behavior**
It should have the right icons instead of duplicated icons.

**Screenshots**
![image](https://github.com/Adyen/adyen-react-native/assets/6399593/d30246b7-9a0a-4dd9-b43c-8d2d066cb48f)

![image](https://github.com/Adyen/adyen-react-native/assets/6399593/23a5c330-a248-4d4f-b5f1-15e3db110494)

**Smartphone: **
 - Device: Pixel 2
 - OS: 11
 - Version 30

If you need an example repo with the example I can do that. but it's straightforward to reproduce

**Comment by descorp** [comment]
Hey @moaead 

Indeed, this seems like odd behaviour on our Android SDK.
If there are **duplicates** in the `brands` collection at the cold start (the icons have not been cached yet), the icons may get mixed up. My theory - there are some android cache hash table collisions.

Thank you for your feedback! I will report this to our android team.
FYI, since this only happens if the `brands` collection contains duplicates (which is not correct), this error will be a low priority.

**UPD**

This seems to be fixed on Android v5.
We are looking to update to latest Android SDK in Q4, so will keep you posted.

**Comment by camil-adyen** [comment]
This has been addresses in v2.0.0-BETA.
