### ISSUE TITLE
New AdyenAction.handle 405 Method Not Allowed

### ISSUE THREAD

**Issue by gunnartorfis** [Adyen/adyen-react-native#368]
**Describe the bug**
When attempting to handle an action for a stored card that uses the frictionless flow, we get a WebView modal showing 405 Method not allowed. The standalone action handling works well for 3DS based saved cards. This was happening in the V2 BETA 1 and is also happening BETA 2 as well. 

I have tried to hardcode GET and POST to the action and both result in the same error. 

**To Reproduce**
1. Pay with a frictionless flow card and save/store the card 
2. Attempt to pay with the stored card, get the error and have the AdyenAction.handle handle it
3. See the WebView modal appear with the error.

**Expected behavior**
The standalone action should be able to handle this.

**Screenshots**
![simulator_screenshot_A3B38B45-E02D-42E5-AD7B-4B2EEFEE552B](https://github.com/Adyen/adyen-react-native/assets/5333875/1bcab837-9701-473a-921b-3a7259926149)

**Smartphone (please complete the following information):**
 - Device: iOS simulator
 - OS: 17.2
 - Version: 2.0 BETA 2

**Comment by descorp** [comment]
Hey @gunnartorfis 

> I have tried to hardcode GET and POST to the action and both result in the same error.

The URL itself is to POST redirect 🤔

This is usually caused by `returnURL` containing **http(s)**, since then our API can't understand if this is native mobile of mobile-web integration. 

---

What are you trying to achieve?

1) If you are looking to have web-based 3DS, you can correct this behaviour by setting [redirectFromIssuerMethod](https://docs.adyen.com/api-explorer/Checkout/71/post/payments#request-redirectFromIssuerMethod) and [redirectToIssuerMethod](https://docs.adyen.com/api-explorer/Checkout/71/post/payments#request-redirectToIssuerMethod) to "GET"

2) To trigger Native 3DS2 - you need to make sure you provide [paymentMethod.threeDS2SdkVersion](https://docs.adyen.com/api-explorer/Checkout/71/post/payments#request-fundRecipient-paymentMethod-threeDS2SdkVersion).
You can get one from [AdyenAction.threeDS2SdkVersion](https://github.com/Adyen/adyen-react-native/blob/develop/example/src/Utilities/payWithCard.js#L18).

**Comment by gunnartorfis** [comment]
Thanks for the details @descorp 
Turns out that we did indeed have https in our returnURL - we hadn't experienced the "redirect" response from an action before, we've always got a 3ds2 action prior to that. 

Swapping it out to our URL Scheme seems to solve it, and then calling AdyenAction.hide() upon success/failure. 
Thanks a lot for the great response, as always 🙏
