### ISSUE TITLE
Appium is unable to detect the on/off recurring button

### ISSUE THREAD

**Issue by iranaahsanali** [Adyen/adyen-react-native#532]
**Describe the bug**
Appium is unable to detect the on/off recurring button within the drop-in card component during integration testing. This prevents us from writing comprehensive test cases for this specific feature.

**To Reproduce**
Steps to reproduce the behaviour:

1. Launch the mobile app.
2. Navigate to the screen containing the drop-in card component.
3. Locate the on/off recurring button within the component.
4. Attempt to interact with the button using Appium's locators.

**Expected behaviour**
Appium should be able to identify and interact with the on/off recurring button within the drop-in card component, allowing for automated testing of its functionality.

**Screenshots**
![Screenshot 2024-09-23 at 7 01 49 PM](https://github.com/user-attachments/assets/9c54a58c-a6db-4591-959c-39f2f541684c)

**Smartphone: *
 - Device: iPhone
 - OS: Any

**Additional context**
"@adyen/react-native": "1.2.0",

**Comment by atmamont** [comment]
Hi @iranaahsanali,

What locator strategy do you use and what element do you look for?
Underlying SDK does not handle "row" click and user must tap on the switch itself.
If you use Appium Inspector, please try drilling down to the switch element and locating it instead of locating the row.

We also plan to use Appium internally and we are keen to make changes that would make testing easier!

**Comment by vikas-kumar-lebara** [comment]
Hi @atmamont,
We are using findElement using "xpath" or "id" to find the toggle button. We cannot rely on offset coordinate of toggle button since we are not executing our testcases on single ios device. If we rely on coordinates then our testcases will fail on executing on different ios devices whose resolution differs. Moreover through appium inspector whenever we try to highlight toggle button it is highlighting the whole row instead of toggle button separately.

**Comment by atmamont** [comment]
Hi, @Vikas-lebara 
I'm commenting to keep this one alive.
Please take a look [here](https://github.com/Adyen/adyen-ios/pull/1865#issuecomment-2418898117) for a short recap of current state.
I will update you when we have a solution that fits both accessibility and testing requirements.

**Comment by atmamont** [comment]
We [found the way](https://github.com/Adyen/adyen-ios/pull/1873) to keep existing VoiceOver capabilities and satisfy tools like Appium, it seems to be a good compromise. We plan to release it soon for iOS SDK and shortly after that for React Native.

If you want to know more, here are some links that explain this is the issue that no one wants to own:
1. [Unable to locate some elements in iOS (same elements can be found via Calabash)](https://discuss.appium.io/t/unable-to-locate-some-elements-in-ios-same-elements-can-be-found-via-calabash/24810)
2. https://github.com/appium/appium/issues/6517
3. [Appium: Under the Hood of WebDriverAgent](https://www.youtube.com/watch?v=4i6x3j1D8C8)

Unfortunately, `xcuitest-driver` Appium uses to traverse a native mobile app, relies purely on accessibility layer so we have to be creative.

**Comment by atmamont** [comment]
@Vikas-lebara 
It's [released](https://github.com/Adyen/adyen-ios/releases/tag/5.13.0) for the main iOS SDK and will be included in the following React Native release.

**Comment by ahsan-ali-lebara** [comment]
@descorp Any tentative timeline for releasing the above Native iOS fix on our React Native SDK?

**Comment by descorp** [comment]
Hey @ahsan-lebara 

This will be included into next release. 
ETA end of November
