### ISSUE TITLE
Adyen 3ds Redirect Url Won't Open in iOS (iPhone)

### ISSUE THREAD

**Issue by ajayjangir0044** [Adyen/adyen-react-native#67]
**Describe the bug**
I have been making Payments API (/payments)to verify the 3ds auth, but I'm unable to open the URL on my iPhone. The URL is opening fine on the web (windows & Mac OS) & android devices.

**To Reproduce**
1. Make a /payments API with the below Payload on a test environment. I am using v69.
2. Payload -->
`{
 "merchantAccount": "yourmerchantaccount",
 "reference": "88424656-60b7",
 "channel": "iOS",
 "metadata": { "mode": "test" },
 "amount": { "value": 0, "currency": "SGD" },
 "paymentMethod": { "storedPaymentMethodId": "B2XK6NB743M84H82", "type": "scheme" }, // enter stored card token value 
 "returnUrl": "https://yourdomain.com/return-url",
 "shopperReference": "88424656-60b7",
 "shopperLocale": "en",
 "shopperEmail": "johndoe@gmail.com",
 "authenticationData": {
   "attemptAuthentication": "always"
  },
 "redirectToIssuerMethod": "GET",
 "shopperInteraction": "ContAuth",
 "recurringProcessingModel": "CardOnFile"
 }`
3. Try to Open the URL from the action object (received in response), in iPhone Physical device or iOS Simulator.
4. See if the URL opened.

**Expected behavior**
The URL should open the 3ds authentication page.
<img width="681" alt="Screenshot 2022-11-10 at 10 57 17 AM" src="https://user-images.githubusercontent.com/56185219/201008129-6e5993b5-c928-40ab-ab7e-e23ae0791149.png">

**Screenshots**
Error Screenshot
![IMG_2691](https://user-images.githubusercontent.com/56185219/201008208-3bbc3077-5193-4716-83e4-0fe73a830476.PNG)

**Comment by ahmetgsu** [comment]
Hey @ajayjangir0044, changing the `returnUrl` schema may help with your issue. The `returnUrl` on ios should be something like that: `yourapp://`

**Comment by descorp** [comment]
Hey @ajayjangir0044 

Thanks for reaching out!
This doesn't look like React Native SDK issue.

I am not able to reproduce this behaviour ~~since same request triggering `native 3DS flow` for me~~. Hence I am assuming that this has to do something with the way how your CA is configured.

Please reach out for [support team](https://www.adyen.help/hc/en-us/requests/new?ticket_form_id=360000705420).
They will either help you directly or will transfer it to our dev team so we can communicate via secure channels.
Make sure to include link to this GitHub issue.  

---

BTW  @ahmetgsu

`returnUrl` on iOS could be an `https` link if it is **Universal Link**. However, you are absolutely correct - custom URL scheme is more reliable hence recommended way of redirect.

**Comment by ajayjangir0044** [comment]
Hey, @ahmetgsu @descorp I'm not able to reproduce the above issue now. Thanks for your support.
